import { Oxygen } from "next/font/google";
import TopNav from "@/components/layout/TopNav";
import MainNavbar from "@/components/layout/MainNavbar";
import Footer from "@/components/layout/Footer";
import "../globals.css";

// const oxygen = Oxygen({
//   variable: "--font-oxygen",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <MainNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
